### ISSUE TITLE
Segmentation fault when folder not existing

### ISSUE THREAD

**Issue by VSack** [hzi-bifo/mdasim#12]
When I try to write the error log into a folder that does not exist, it results in a segmentation fault (see below). This should be fixed quite easily but I'm not sure if this would result in a new release and if so, if I should fix it together with issue #11 

```
/bin/bash: Line 1: 29855 Segmentation fault  mdasim --input=output/pyvolve/Gorilla_0.fasta --output=output/mdasim/ --log=deltas/mdasim/copy-errors_Gorilla_0.tsv --coverage=100 --frgLngth=1000 --stepSize=100 --primers=examples/primerList.fasta > output/logs/Gorilla_0_mdasim.log
```

**Comment by dlaehnemann** [comment]
Thanks for tracking this here, exactly the right thing to do!

As this folder issue is only a minor change that will not affect the output generated, I'd say this only warrants an increase in the last number of the version string. #11 will in turn change the output, but also is only a bug fix, so to me would be middle number update.

But I agree, once you work on this, it does make sense to address both bugs at once -- also, it's easier not to have to create a new release and updated bioconda recipe for every incremental change. So address both of them at once and then update the version number of the next release to `2.1.0`

**Comment by VSack** [comment]
Same thing for the output files, thus this bug was already present in 1.2. As soon as I try to run something like
```
bin/mdasim --input=examples/test.fa --primers=examples/primerList.fasta --coverage=20 --log=mylog.log -O=somefolder/someotherfolder/myfile
``` 
I'll get an error after the amplification is done:
```
Error: failed to open file somefolder/someotherfolder/myfileAmplicons.fasta in mode wt.
```
The thing with creating directories, unlike `fopen()`, it's not part of ANSI standard C, since `mkdir()` is POSIX-specific. There seems to be no ANSI way to create directories. Thus, we have a number of options:
* limit the usage of MDAsim to Linux and implement linux-specific directory creation
* test if the folder exitsts and warn the user before the amplification process, if it is missing. The user would have to create the path manually.
* write some python wrapper script that creates the folders if needed and then runs MDAsim. However, this would create an extra dependency.
* use the [predefined macros](https://stackoverflow.com/questions/142508/how-do-i-check-os-with-a-preprocessor-directive) to [create folders for different operating systems](https://stackoverflow.com/questions/23271990/how-to-create-a-folder-in-c-need-to-run-on-both-linux-and-windows). This would be the cleanest solution I guess.

**Comment by dlaehnemann** [comment]
I think solution 2 is both the easiest to implement and probably also the cleanest one. The macros solution (4) that you reference e.g. doesn't include MacOS...

So if this is a quick and easy check, I would opt for checking for the presence of the output and logging folder and to throw an informative error if either does not exist, suggesting to create the directory.

**Comment by dlaehnemann** [comment]
Thanks, looks good!
