### ISSUE TITLE
Header for error log

### ISSUE THREAD

**Issue by VSack** [hzi-bifo/mdasim#13]
We should create a header in the error log file, which specifies the original sequence file, for easier (manual) mapping afterwards.

**Comment by VSack** [comment]
Header does not specify input file now, the log file name should do this since it'd be more coherent with the other log files of [ePySCOPE](https://github.com/hzi-bifo/ePySCOPE).

**Comment by dlaehnemann** [comment]
Sounds reasonable, but I think I would just go with more information / more self-documentation here -- people might use MDAsim 2 in different contexts and might not directly make sure they document this. So I would just introduce another header line with something like:

```
#input sequence file: <input_seq_fasta_filename>
```

Should be quick enough, right?

**Comment by dlaehnemann** [comment]
Thanks! Looks good!
