### ISSUE TITLE
clean up and document code

### ISSUE THREAD

**Issue by dlaehnemann** [hzi-bifo/mdasim#16]
As mere output testing doesn't seem to get us anywhere, to fix issue #15 we have to get a more detailed understanding of what exactly the code does. We therefore have to go through the code, comment everything and refactor where necessary for improved clarity. For documentation of functions, we should adopt Doxygen syntax, following this guide:

https://developer.lsst.io/cpp/api-docs.html

**Comment by dlaehnemann** [comment]
OK, so I did not get any further than `include/sequence.h` and `src/sequence.C` so far. If you find the time, @VSack, feel free to tackle `src/mdasim.C` et al. and I'll let you know should I find more time to wade through code...

**Comment by VSack** [comment]
I started commenting and refactoring `mdasim.C` and `mdasim.h`. As you can see in [mdasim.C](https://github.com/hzi-bifo/mdasim/blob/3a30ad50172cd95c098402c8dcc929b7b5dca637/src/mdasim.C) there are quite a few methods that I marked with `@deprecated` since they seem to be no longer in use. Should I remove this unused code or do you want to keep it ... idk, for future purposes/reference?

**Comment by dlaehnemann** [comment]
From a quick look, I would do the following:

The `loadFragmentList` function is definitely unused:
https://github.com/hzi-bifo/mdasim/blob/3a30ad50172cd95c098402c8dcc929b7b5dca637/src/mdasim.C#L513

It corresponds to the respective part in the main function that has been commented out:
https://github.com/hzi-bifo/mdasim/blob/3a30ad50172cd95c098402c8dcc929b7b5dca637/src/mdasim.C#L1252-L1274

So this is functionality that was either never finished or actively retired at some point, and we probably won't need it any more. So these two I would remove in one descriptive commit.

All of the other functions marked as `deprecated` / `unused` are some form of `writeXYZ` and I'm assuming these are functions used for debugging output of intermediate states of the respective lists. So I would keep them and annotate them as debugging functions. Also, you might use them yourself, to better understand the behaviour of some of the code.

Does this make sense?

**Comment by dlaehnemann** [comment]
Thanks for all the commenting, already. I'll go through the whitespace issues once you are through with the latest changes and then close this issue.

**Comment by VSack** [comment]
I think I'm done with debugging for now, so you can go through that whitespace issue if you want and once you find the time, it'd be great if you could put the new version up on Conda so I can adjust the pipeline to the new output and continue with the joint logging issue.

**Comment by dlaehnemann** [comment]
Thanks for the heads up, will do! ;)

**Comment by dlaehnemann** [comment]
I have now done the whitespace cleanup (tabs to 2 whitespaces each), have done some version number parsing cleanup and created the new release. So will close this issue for now -- should we want to or need to do some more code cleanup in the future, we can either reopen this issue or start a new (and more specific one).
