### ISSUE TITLE
Error log positions != Fragment output positions

### ISSUE THREAD

**Issue by VSack** [hzi-bifo/mdasim#18]
The positions in the output are 0-based since we solved #15. The error log still contains 1-based positions though. I think we should change this to 0-based positions for coherence and to avoid confusions and off-by-one errors for potential users further down any processing workflow. This should be fixed quickly but I wanted to check with you first.

**Comment by dlaehnemann** [comment]
As it seems that in Epyscope we will not be able to have consistency regarding 0-base and 1-base as logging output of the different tools in different substeps (see [the relevant section in the README.md](https://github.com/hzi-bifo/ePySCOPE/blob/master/README.md#deltas-folder)), we should just make sure that we are consistent within the mdasim output.

But I think the joint logging output in the end will be 0-based, right? So then we should probably stick to that and I agree with you that the mdasim error log should be 0-based.
