### ISSUE TITLE
minor cleanups

### ISSUE THREAD

**Issue by dlaehnemann** [hzi-bifo/mdasim#3]
[ ] remove pre-compiled binary and other files produced by make, i.e. put the repo in the state it is in after a `make clean` -- this will remove this step from the build process
[ ] change `README_mdasim.txt` to `README.md` to make it auto-parseable by GitHub (adjust the formatting to MarkDown and maybe make the list of contents interactive by adding document-internal links)

**Comment by dlaehnemann** [comment]
Thanks for the cleanup, it looks good and explains what we changed very well.

One minor thing (and sorry that I reopen this issue, but it should be fixed quickly):

I don't think my name needs to be the first thing in the README.md at <https://github.com/hzi-bifo/mdasim/blob/0bce4c7d31445432e043946a46dca9e9a2b28c05/README.md#mdasim-13>. I would remove my name and the affiliation there and instead just link to the CREDITS_mdasim.txt (and also the LICENSE.txt) after giving the citation of the original MDAsim paper in that first section of the README.md.

**Comment by VSack** [comment]
I restructured the whole thing, please take another look if you find the time, to confirm that this is how you had it in mind.

**Comment by dlaehnemann** [comment]
Yes, very nice and much cleaner, this way. One thing I realised, again: The current version does not adhere to semantic versioning (see <https://semver.org/>). But I'll close this issue and move this to a new one, #5.
